### ISSUE TITLE
Whether video enhancement will have a bit rate increase ?

### ISSUE THREAD

**Issue by wrenchonline** [RyanXingQL/STDF-PyTorch#11]
I designed a [REPVGG](https://github.com/wrenchonline/fastvepvgg) network with low latency and 20ms inference at NPU, but the bit rate seems to be uncertain with the quality enhancement？Does video enhancement not handle restored file sizes?

**Comment by RyanXingQL** [comment]
Most video quality enhancement methods do not control the output size.
In my view,
(1) Most MSE/PSNR-oriented methods may not increase the output size, or even decrease the output size, since the textural areas would be blurred.
(2) Most GAN-based methods may increase the output size, since the high-frequency components would be enhanced.
